<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPvUIHY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPvUIHY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPPvUIHY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPPvUIHY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPPvUIHY\App_KernelDevDebugContainer([
    'container.build_hash' => 'PPvUIHY',
    'container.build_id' => 'c07dd48a',
    'container.build_time' => 1681991118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPvUIHY');
