# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute
logout:
    path: /logout
register:
    path: /register
    controller: App\Controller\RegistrationController::register


